// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKrXURTVygfYeQEEY1YMCHacYan66_-6A',
    appId: '1:307134434935:android:ef91db9b571cb93b170072',
    messagingSenderId: '307134434935',
    projectId: 'naukriwala-455909',
    databaseURL: 'https://naukriwala-455909-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'naukriwala-455909.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzggw69OmhX80JIZrh1qCdtYeEMl1TG84',
    appId: '1:307134434935:ios:a2916cc885949ded170072',
    messagingSenderId: '307134434935',
    projectId: 'naukriwala-455909',
    databaseURL: 'https://naukriwala-455909-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'naukriwala-455909.firebasestorage.app',
    androidClientId: '307134434935-v7up21dbm3it15io8qecu8b0giufhohr.apps.googleusercontent.com',
    iosBundleId: 'com.naukariwala.avr',
  );

}